

const galardon = [
    "Película Favorita.",
    "Actor/a Favorito.",
    "Director Favorito.",
    "Película con la que más lloras (si no has llorado nunca con el cine, eres un poco insensible :P)",
    "Película que odias y todo el mundo ama.",
    "Saga cinematográfica que has abandonado y por qué.",
    "Género cinematográfico favorito.",
    "Género cinematográfico que menos te guste.",
    "Película de tu infancia.",
    "¿Te has forrado la carpeta con cosas de películas?",
    "Pareja cinematográfica favorita.",
    "¿Qué película te gustaría protagonizar?",
    "Mayor locura que has hecho por una película.",
    "Mejor adaptación cinematográfica.",
    "Peor adaptación cinematográfica.",
    "Actor que más odias y con el que cambias de canal.",
    "Película con la que te quedaste dormido y no sabes el motivo.",
    "Malo cinematográfico favorito.",
    "Películas pendientes.",
    "Frase de película con la que vivas enganchado.",
]
const categories = [
    "+18",
    "Acción",
    "Action & Adventure",
    "Animación",
    "Aventura",
    "Bélica",
    "Castellano",
    "Ciencia ficción",
    "CINECALIDAD",
    "CINECALIDAD TOP",
    "Comedia",
    "Crimen",
    "descargacineclasico tv",
    "Documental",
    "Drama",
    "Familia",
    "Fantasía",
    "Historia",
    "Kids",
    "Latino",
    "MARVEL",
    "Mas Vistas",
    "Misterio",
    "Música",
    "película de la televisión",
    "Película de TV",
    "Peliculas Alemanas",
    "Peliculas Argentinas",
    "Peliculas Australianas",
    "Peliculas Bolivianas",
    "Peliculas Brasileñas",
    "Peliculas Canadienses",
    "Peliculas Chilenas",
    "Peliculas China",
    "Peliculas Colombianas",
    "Peliculas Coreanas",
    "Peliculas Cristianas",
    "Películas de Chequia",
    "Peliculas de Guatemala",
    "Peliculas de Islandia",
    "Peliculas de Reino Unido",
    "Peliculas de Rusia",
    "Peliculas de Sudafrica",
    "Peliculas En Ingles",
    "Peliculas Españolas",
    "Peliculas Estadounidenses",
    "Peliculas Francesas",
    "Peliculas Indias",
    "Peliculas Italianas",
    "Peliculas Japonesas",
    "Peliculas Noruegas",
    "Peliculas Panameñas",
    "Peliculas Peruanas",
    "Peliculas subtituladas",
    "Peliculas Tailandesa",
    "Peliculas Taiwanesas",
    "Peliculas Uruguayas",
    "Próximamente",
    "Reality",
    "Romance",
    "Sci-Fi & Fantasy",
    "Series Animadas Gratis",
    "Series En Español Castellano",
    "Series En Español Latino",
    "Series Subtituladas",
    "Suspense",
    "Terror",
    "War & Politics",
    "Western",
]
const moivesNames = [
    "2003 - 1986",
    "Buscando a Nemo(2003)",
    "Ciudad de Dios(2002)",
    "Hable con ella(2002)",
    "El Señor de los Anilllos(2001 – 2003)",
    "Kandahar(2001)",
    "La mirada de Ulises(1995)",
    "Chunking Express(1994)",
    "Drunken Master II(1994)",
    "Pulp Fiction(1994)",
    "Adiós a mi concubina(1993)",
    "La lista de Schindler(1993)",
    "Leolo(1992)",
    "Sin Perdón(1992)",
    "Uno de los nuestros(1990)",
    "Muerte entre las flores(1990)",
    "El decálogo(1989)",
    "Nakayan(1987)",
    "El cielo sobre Berlín(1987)",
    "La mosca(1986)",
    "El detective cantante(1986)",
    "1985 – 1966",
    "Brazil(1985)",
    "La Rosa púrpura del Cairo(1985)",
    "Blade Runner(1992)",
    "E.T.El extraterrestre(1982)",
    "Berlin Alexanderplatz(1980)",
    "Mi tío de América(1980)",
    "Toro salvaje(1980)",
    "La Guerra de las Galaxias(1977)",
    "Taxi Driver(1976)",
    "Barry Lyndon(1975)",
    "Chinatown(1974)",
    "La noche americana(1973)",
    "El Padrino(Parte I y II)(1972, 1974)",
    "Aguirre, la cólera de Dios(1972)",
    "El discreto encanto de la burguesía(1972)",
    "A touch of Zen(1971)",
    "Érase una vez en América(1968)",
    "Bonnie and Clide(1967)",
    "Mouchette(1967)",
    "Trenes rigurosamente vigilados(1966)",
    "1966 – 1954",
    "El bueno, el feo y el malo(1966)",
    "Persona(1966)",
    "Bande à part(1964)",
    "Teléfono rojo, volamos hacia Moscú(1964)",
    "Qué noche la de aquel día(A hard day’s night)(1964)",
    "Charada(1963)",
    "8 y ½ (1963)",
    "Lawrence de Arabia(1962)",
    "El mensajero del miedo(1962)",
    "Yoyimbo(1961)",
    "Psicosis(1960)",
    "Los cuatrocientos golpes(1959)",
    "Con faldas y a lo loco(1959)",
    "Pyassa(1957)",
    "Chantaje en Broadway(1957)",
    "La invasión de los ladrones de cuerpos(1956)",
    "Centauros del desierto(1956)",
    "La trilogía de Apu(1955, 1956, 1959)",
    "Sonrisas de una noche de verano(1955)",
    "La ley del silencio(1954)",
    "1953 – 1940",
    "Cuentos de Tokio(1953)",
    "Historias de la luna pálida de agosto(1953)",
    "Vivir(1952)",
    "Cantando bajo la lluvia(1952)",
    "Umberto D(1952)",
    "Un tranvía llamado deseo(1951)",
    "En un lugar solitario(1950)",
    "Ocho sentencias de muerte(1949)",
    "Al rojo vivo(1949)",
    "Retorno al pasado(1949)",
    "Qué bello es vivir(1946)",
    "Encadenados(1946)",
    "Les enfants du paradise(1945)",
    "Detour(1945)",
    "Perdición(1944)",
    "Cita en San Luis(1944)",
    "Casablanca(1942)",
    "Ciudadano Kane(1941)",
    "Las tres noches de Eva(1941)",
    "Luna nueva(1940)",
    "1940 – 1924",
    "Pinocho(1940)",
    "El bazar de las sorpresas(1940)",
    "Ninotchka(1939)",
    "Olimpia I y II(1938)",
    "La pícara puritana(1937)",
    "Margarita Gautier(1936)",
    "Le Crime de Monsieur Lange(1936)",
    "Desengaño(1936)",
    "En alas de la danza(1936)",
    "La novia de Frankenstein(1935)",
    "It's A Gift (1934)",
    "Baby Face(1933)",
    "King Kong(1933)",
    "Luces de la ciudad(1931)",
    "El Cameraman(1929)",
    "Y el mundo marcha… (1928)",
    "La última orden(1928)",
    "Metrópolis(1927)",
    "El joven Sherlock Holmes(1924)",
]

module.exports = {
    totalMovies: moivesNames.length,
    galardon,
    movies: moivesNames,
    categories
}